global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrap_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "localhost:9090" ]
  
  - job_name: note-service
    static_configs:
      - targets: [ "host.docker.internal:2112" ]